services:
  - type: web
    name: ai-watermark-app
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      apt-get update && apt-get install -y libgl1 poppler-utils
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        sync: false